// This file is generated by: npx supabase gen types typescript --project-id <ref>
// After linking your Supabase project, replace this with the generated output.
// For now, these hand-crafted types match the 001_initial_schema.sql migration exactly.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export type UserRole = 'admin' | 'user'
export type InitiativeStatus = 'planning' | 'in_progress' | 'on_hold' | 'completed' | 'cancelled'
export type TaskStatus = 'todo' | 'in_progress' | 'in_review' | 'done' | 'cancelled'
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent'
export type PreserviceStage =
  | 'as_is_study'
  | 'gap_analysis'
  | 'solution_scope'
  | 'technical_financial_offer'
export type AiSummaryType = 'weekly_standup' | 'outreach_draft'
export type AiSummaryStatus = 'pending' | 'generating' | 'done' | 'error'
export type AiSummaryTrigger = 'manual' | 'n8n'

/** The structured 4-section payload stored in ai_summaries.report_content */
export interface WeeklySummaryReport {
  standup_digest: string
  task_progress: string
  strategy_update: string
  action_items_risks: string
}

export interface Profile {
  id: string
  full_name: string
  email: string
  role: UserRole
  department: string | null
  job_title: string | null
  avatar_url: string | null
  created_at: string
  updated_at: string
}

export interface Initiative {
  id: string
  name: string
  description: string | null
  status: InitiativeStatus
  owner_id: string
  start_date: string | null
  target_date: string | null
  layer_see: boolean
  layer_know: boolean
  layer_decide: boolean
  created_at: string
  updated_at: string
}

export interface DailyUpdate {
  id: string
  user_id: string
  update_date: string
  did_today: string
  blockers: string | null
  plan_tomorrow: string | null
  created_at: string
  updated_at: string
}

export interface ShmTask {
  id: string
  title: string
  description: string | null
  status: TaskStatus
  priority: TaskPriority
  assignee_id: string
  initiative_id: string | null
  due_date: string | null
  created_at: string
  updated_at: string
}

export interface ShmOutreach {
  id: string
  contact_name: string
  company: string
  contact_email: string | null
  stage: PreserviceStage
  notes: string | null
  last_contact_date: string | null
  owner_id: string
  created_at: string
  updated_at: string
}

export interface AiSummary {
  id: string
  summary_type: AiSummaryType
  reference_id: string | null
  week_start: string | null
  /** ISO date string for the last day of the week this summary covers */
  week_end: string | null
  content: string
  /** Structured 4-section report; null for non-weekly summary types */
  report_content: WeeklySummaryReport | null
  /** Generation lifecycle status */
  status: AiSummaryStatus
  /** How the generation was triggered */
  triggered_by: AiSummaryTrigger
  generated_by: string
  created_at: string
}

export interface Template {
  id: string
  name: string
  description: string | null
  category: string
  layer_see: boolean
  layer_know: boolean
  layer_decide: boolean
  config: Record<string, unknown>
  created_by: string
  created_at: string
  updated_at: string
}

// Join types (with related profile data)
export interface DailyUpdateWithProfile extends DailyUpdate {
  profiles: Pick<Profile, 'full_name' | 'avatar_url'>
}

export interface ShmTaskWithProfile extends ShmTask {
  profiles: Pick<Profile, 'full_name' | 'avatar_url'>
}

export interface ShmOutreachWithProfile extends ShmOutreach {
  profiles: Pick<Profile, 'full_name'>
}

export interface InitiativeWithProfile extends Initiative {
  profiles: Pick<Profile, 'full_name'>
}

export interface TemplateWithProfile extends Template {
  profiles: Pick<Profile, 'full_name'>
}

type TableDef<Row, Insert, Update> = {
  Row: Row
  Insert: Insert
  Update: Update
  Relationships: []
}

// Supabase Database type (used by the client for full type-safety)
// Replace with `supabase gen types typescript` output after linking your project.
export interface Database {
  public: {
    Tables: {
      profiles: TableDef<
        Profile,
        Omit<Profile, 'created_at' | 'updated_at'>,
        Partial<Omit<Profile, 'id' | 'created_at' | 'updated_at'>>
      >
      initiatives: TableDef<
        Initiative,
        Omit<Initiative, 'id' | 'created_at' | 'updated_at'>,
        Partial<Omit<Initiative, 'id' | 'created_at' | 'updated_at'>>
      >
      daily_updates: TableDef<
        DailyUpdate,
        Omit<DailyUpdate, 'id' | 'created_at' | 'updated_at'>,
        Partial<Omit<DailyUpdate, 'id' | 'created_at' | 'updated_at'>>
      >
      shm_tasks: TableDef<
        ShmTask,
        Omit<ShmTask, 'id' | 'created_at' | 'updated_at'>,
        Partial<Omit<ShmTask, 'id' | 'created_at' | 'updated_at'>>
      >
      shm_outreach: TableDef<
        ShmOutreach,
        Omit<ShmOutreach, 'id' | 'created_at' | 'updated_at'>,
        Partial<Omit<ShmOutreach, 'id' | 'created_at' | 'updated_at'>>
      >
      ai_summaries: TableDef<
        AiSummary,
        Omit<AiSummary, 'id' | 'created_at'> & { generated_by?: string },
        Partial<Omit<AiSummary, 'id' | 'created_at'>>
      >
      templates: TableDef<
        Template,
        Omit<Template, 'id' | 'created_at' | 'updated_at'>,
        Partial<Omit<Template, 'id' | 'created_at' | 'updated_at'>>
      >
    }
    Functions: {
      is_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
    }
    Enums: Record<string, never>
  }
}
